### ISSUE TITLE
Processing Lag

### ISSUE THREAD

**Issue by ggcaetano** [ggcaetano/gh-actions-exercise#1]
# Improvement proposition
### Jobs should be run in parallel to increase processing speed, considering compute resources are not really impacted.
```
name: Test and Build project
on:
  push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test project
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."  
```
